<table align="left" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Inclass - Lab <br> (Day 1) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#For Loop)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [11]:
import numpy as np
import pandas as pd
from numpy.random import randint

In [29]:
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [31]:
num1 = np.array(list_temperature)
num1


array([3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [11]:
    weights = [74.2, 85, 74, 67.9, 52, 70.5,  86, 51.8, 64, 82]
    

In [12]:
num1 = np.array(weights)
print("weight greater than 68 :-",num1[num1>68])


<IPython.core.display.Javascript object>

weight greater than 68 :- [74.2 85.  74.  70.5 86.  82. ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [18]:
from numpy.random import randint

In [139]:
np.random.seed(0)
np.random.randint(20,40,10)



array([32, 35, 20, 23, 23, 27, 29, 39, 38, 24])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [3]:
import math


In [84]:
a=np.arange(1,6)
a**5

array([   1,   32,  243, 1024, 3125])

In [5]:
b = np.arange(1,10)
b**2


<IPython.core.display.Javascript object>

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [88]:
a=np.arange(51,100,2)
a

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

In [7]:
even_aft_50 = np.arange(50,100,2)
even_aft_50

<IPython.core.display.Javascript object>

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [115]:
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
A    

[[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [123]:
B = np.array(A)
B

array([[ 1,  4,  8],
       [ 5,  7,  3],
       [ 9, 14,  2]])

In [122]:
sum(B)

array([15, 25, 13])

In [11]:
    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
    B = np.array(A)
    sum(B)
    print(B,sum(B))
    

<IPython.core.display.Javascript object>

[[ 1  4  8]
 [ 5  7  3]
 [ 9 14  2]] [15 25 13]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [12]:
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
    

In [125]:
num1 = np.array(num)

In [131]:
for i in num1:
    print(i % 8)

2
7
2
6
0
3
5
0
4


In [14]:
num1 = np.array(num)
num1

<IPython.core.display.Javascript object>

array([42, 87, 90, 14, 32, 75, 61, 80, 92])

In [15]:
for i in num1:
    print(i%10)

2
7
0
4
2
5
1
0
2


<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [159]:
a=randint(1,40,20).reshape(5,4)


array([[19, 16, 12, 39],
       [30,  2, 32, 25],
       [25,  4, 19,  4],
       [13, 39, 36, 23],
       [ 6, 24, 33, 12]])

In [20]:
a2 = randint(1,40,20).reshape(5,4)
a2

array([[32, 18,  7,  7],
       [31, 35, 20, 17],
       [25, 33, 14, 36],
       [28, 26, 32, 16],
       [ 3, 15, 27, 27]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [13]:
prices_monday = [10, 30, 50, 60, 90]

prices_tuesday = [50, 20, 80, 125, 10, 70]

In [18]:

  print(np.intersect1d(prices_monday , prices_tuesday))

<IPython.core.display.Javascript object>

[10 50]


In [22]:
prices_monday = [10, 30, 50, 60, 90]

prices_tuesday = [50, 20, 80, 125, 10, 70]

In [24]:
print(np.intersect1d(prices_monday , prices_tuesday))

<IPython.core.display.Javascript object>

[10 50]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [20]:
weights = [57, 69, 54, 65 ,71, 62, 56]

heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

BMI = weights/(heights/100)**2

BMI

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [37]:
group_bmi = [["a" ,57 , 1.59],["b" ,69 , 1.75],["c" ,54 , 1.66],["d",65 , 1.74],
             ["e" ,71 , 1.64],["f" , 62 , 1.72],["g" ,56 , 1.53]]
BMI = [group_bmi[0][1]/((group_bmi[0][2]/100*100)**2)
      for i in group_bmi]
BMI

[22.54657648036074,
 22.54657648036074,
 22.54657648036074,
 22.54657648036074,
 22.54657648036074,
 22.54657648036074,
 22.54657648036074]

In [27]:
person_data = [
              ['John', 84.9, 184],
              ['Ryan', 81.8, 177],
              ['Bobby', 86.1, 190],
              ['Lambda Llama', 140, 180],      # Name, Weights, Heights
              ['Pete', 92.2, 188],
              ['Esther', 69.6, 159],
              ['Jane', 72.0, 166],
              ['Samantha', 51.3, 162]]

In [29]:
BMI = [person_data[0][1]/((person_data[0][2]/100)**2)
      for i in person_data]
BMI

[25.07679584120983,
 25.07679584120983,
 25.07679584120983,
 25.07679584120983,
 25.07679584120983,
 25.07679584120983,
 25.07679584120983,
 25.07679584120983]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [25]:
# type your code here
array1 = np.array([[3, 4], [8, 2],[5, 9]])
print("initial array",array1 )
array3 = np.array([5,7])

array2 = np.vstack((array1, array3))
print("final array", array2)

<IPython.core.display.Javascript object>

initial array [[3 4]
 [8 2]
 [5 9]]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

final array [[3 4]
 [8 2]
 [5 9]
 [5 7]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [26]:
# type your code here
np.identity(5)

<IPython.core.display.Javascript object>

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [43]:
# type your code here
M = np.array([[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]])
M.transpose()
   
    

<IPython.core.display.Javascript object>

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [49]:
# type your code here
A1 = np.array([[5, 9], [7, 6]])

A2 = np.array([[8,-7], [0,4]])

print("horizontally :", np.concatenate((A1,A2),axis=0))
print("vertically   :", np.concatenate((A1,A2),axis=1))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

horizontally : [[ 5  9]
 [ 7  6]
 [ 8 -7]
 [ 0  4]]


<IPython.core.display.Javascript object>

vertically   : [[ 5  9  8 -7]
 [ 7  6  0  4]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [54]:
# type your code here
A1 = np.array([[-81, 75, 40], [27, 67, 52]])

A2 = np.array([[15, 54,0], [39, 56,0]])
print("horizontally :", np.concatenate((A1,A2),axis=0))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

horizontally : [[-81  75  40]
 [ 27  67  52]
 [ 15  54   0]
 [ 39  56   0]]


<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [57]:
# type your code here
A = ([[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]])
newarr = np.array_split(A, 3)
print(newarr)

<IPython.core.display.Javascript object>

[array([[ 4,  7],
       [ 2, -3]]), array([[8, 1],
       [0, 9]]), array([[ 5, -1],
       [ 8,  3]])]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [60]:
B = ([[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]])
newarr = np.array_split(B,2)
print(newarr)

<IPython.core.display.Javascript object>

[array([[ 8,  7,  0,  9],
       [ 2, -3,  5, 10]]), array([[ 8,  5, -1,  3]])]


<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [0]:
# type your code here
# Python3 code to demonstrate working of
# Extract Combination Mapping in two lists
# using zip() + product()
from itertools import product

# initialize lists
test_list1 = [3, 4, 5]
test_list2 = ['x', 'y']

# printing original lists
print("The original list 1 is : " + str(test_list1))
print("The original list 2 is : " + str(test_list2))

# Extract Combination Mapping in two lists
# using zip() + product()
res = list(list(zip(test_list1, ele)) for ele in product(test_list2, repeat = len(test_list1)))

# printing result
print("Mapped Combination result : " + str(res))


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [0]:
# type your code here
